services:
  - type: web
    name: wehave-ai-backend
    env: node
    buildCommand: cd backend && yarn install && yarn build
    startCommand: cd backend && PORT=3001 yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3001
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true

  - type: web
    name: wehave-ai-frontend
    env: node
    buildCommand: cd frontend && yarn install && yarn build
    startCommand: cd frontend && PORT=3000 yarn preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://wehave-ai-backend.onrender.com
      - key: PORT
        value: 3000
    plan: free
    autoDeploy: true 