services:
  - type: web
    name: wehave-ai-backend
    env: node
    buildCommand: |
      yarn install
      cd backend
      yarn install
      yarn add -D @types/node@20.11.24 typescript@5.3.3
      yarn build
    startCommand: cd backend && PORT=3001 yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3001
    healthCheckPath: /api/health
    plan: free

  - type: web
    name: wehave-ai-frontend
    env: node
    buildCommand: |
      yarn install
      cd frontend
      yarn install
      yarn build
    startCommand: cd frontend && PORT=3000 yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    plan: free 