services:
  - type: web
    name: wehave-ai-backend
    env: node
    buildCommand: npm install && cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/health

  - type: web
    name: wehave-ai-frontend
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://wehave-ai-backend.onrender.com 